NAME[0]="Fahim"
NAME[1]="Sultan"
NAME[2]="Mahnaz"
NAME[3]="Ayan"
NAME[4]="Daisy"
echo "First Index: ${NAME[0]}"
echo "Second Index: ${NAME[1]}"
echo "All the items: ${NAME[*]}"
echo "Another system of all the items: ${NAME[@]}"
